
version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - ecommerce-network

  service-discovery-container:
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ecommerce-network
    depends_on:
      - zipkin-container

  cloud-config-container:
    image: selimhorri/cloud-config-ecommerce-boot:0.1.0
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - zipkin-container

  api-gateway-container:
    image: selimhorri/api-gateway-ecommerce-boot:0.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  proxy-client-container:
    image: selimhorri/proxy-client-ecommerce-boot:0.1.0
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  order-service-container:
    image: selimhorri/order-service-ecommerce-boot:0.1.0
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  payment-service-container:
    image: selimhorri/payment-service-ecommerce-boot:0.1.0
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  product-service-container:
    image: selimhorri/product-service-ecommerce-boot:0.1.0
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  user-service-container:
    image: selimhorri/user-service-ecommerce-boot:0.1.0
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

  favourite-service-container:
    image: selimhorri/favourite-service-ecommerce-boot:0.1.0
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - ecommerce-network
    depends_on:
      - service-discovery-container
      - cloud-config-container

networks:
  ecommerce-network:
    driver: bridge



