# Default values for payment-service
replicaCount: 2

image:
  repository: gcr.io/your-gcp-project-id/payment-service
  tag: latest-master
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8083
  targetPort: 8083

ingress:
  enabled: true
  className: "gce"
  hosts:
    - host: payment-service.your-domain.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Configuración específica del servicio
config:
  springProfiles: production
  serverPort: 8083
  
# Health checks
healthCheck:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 90
  periodSeconds: 30
