apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery-config
  namespace: staging
data:
  SPRING_PROFILES_ACTIVE: "stage"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: staging
  labels:
    app: service-discovery
    environment: staging
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        environment: staging
        version: v1
    spec:
      nodeSelector:
        pool: microservices-pool
      containers:
      - name: service-discovery
        image: selimhorri/service-discovery-ecommerce-boot:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: service-discovery-config
              key: SPRING_PROFILES_ACTIVE
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: staging
  labels:
    app: service-discovery
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-discovery-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-discovery
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
