apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: staging
  labels:
    app: user-service
    environment: staging
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        environment: staging
        version: v1
    spec:
      nodeSelector:
        pool: microservices-pool
      containers:
      - name: user-service
        image: us-central1-docker.pkg.dev/ecommerce-backend-1760307199/ecommerce-microservices/user-service:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8700
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_FLYWAY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: SPRING_FLYWAY_ENABLED
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
