# Default values for favourite-service
replicaCount: 2

image:
  repository: gcr.io/your-gcp-project-id/favourite-service
  tag: latest-master
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8085
  targetPort: 8085

ingress:
  enabled: true
  className: "gce"
  hosts:
    - host: favourite-service.your-domain.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Configuración específica del servicio
config:
  springProfiles: production
  serverPort: 8085
  
# Health checks
healthCheck:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 90
  periodSeconds: 30
