fullnameOverride: discovery

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/ecommerce-backend-1760307199/ecommerce-microservices/service-discovery
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8761

readinessProbe:
  path: /actuator/health
  port: 8761
  initialDelaySeconds: 10
  periodSeconds: 30

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_ZIPKIN_BASE_URL
    value: http://zipkin:9411/
  - name: eureka.client.service-url.defaultZone
    value: http://discovery:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: discovery
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "false"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "false"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"