# Default values for shipping-service
replicaCount: 1

image:
  repository: geoffrey0pv/shipping-service
  tag: latest-master
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8084
  targetPort: 8084

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Configuración específica del servicio
config:
  springProfiles: dev
  serverPort: 8084
  
# Health checks
healthCheck:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 30
