fullnameOverride: user-service

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/ecommerce-backend-1760307199/ecommerce-microservices/user-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8700 

readinessProbe:
  path: /user-service/actuator/health 
  port: 8700
  initialDelaySeconds: 60 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe: 
  path: /user-service/actuator/health
  port: 8700
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: SPRING_ZIPKIN_BASE_URL
    value: "http://zipkin:9411/"
  - name: eureka.client.service-url.defaultZone
    value: "http://discovery:8761/eureka"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: "user-service"
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "false"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "false"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: EUREKA_CLIENT_ENABLED  
    value: "false"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE  
    value: "health,info,metrics"