# Values for product-service
service:
  name: "product-service"
  type: ClusterIP
  port: 8500
  targetPort: 8500

image:
  repository: "geoffrey0pv/product-service"
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8500"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://service-discovery:8761/eureka"
  SPRING_CLOUD_CONFIG_URI: "http://cloud-config:8888"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3