# Values for service-discovery (Eureka Server)
image:
  repository: "geoffrey0pv/service-discovery"
  pullPolicy: IfNotPresent
  tag: "v2"

replicaCount: 1

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

env:
  SPRING_PROFILES_ACTIVE: "dev"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

# Eureka Server no necesita health checks muy agresivos
# TEMPORALMENTE DESHABILITADO para debugging
# livenessProbe:
#   httpGet:
#     path: /actuator/health
#     port: http
#   initialDelaySeconds: 60
#   periodSeconds: 30
#   timeoutSeconds: 10
#   failureThreshold: 3

# readinessProbe:
#   httpGet:
#     path: /actuator/health
#     port: http
#   initialDelaySeconds: 30
#   periodSeconds: 15
#   timeoutSeconds: 5
#   failureThreshold: 3